### ISSUE TITLE
Running your samples in 2.2

### ISSUE THREAD

**Issue by uwefms** [SQL-MisterMagoo/BlazorTest#6]
Hi MisterMagoo,

   thanks for providing these blazor samples. I had problems to compile them because there was no chance for me to get 2.2.100-preview2-009404 SDK. According to #5666 there is no way to compile the app in an 2.2 SDK. So I tried to downgrade to 2.1. For this I created a brand new blazor app to copy your stuff in and noticed that in the meantime a new preview had been added. (0.8.0-preview1-20181126.4) This version has quite some changes compared to the former ones:

Microsoft.AspNetCore.Blazor becomes Microsoft.AspNetCore.Components

BlazorComponent becomes ComponentBase ... and some other changes to include in core 3.0

I tried to change your project but I got stuck at the treeview. (Program cannot find person in tree.chtml)

`<span class="oi oi-plus" onclick="@{()=>OnClick(person)}"> @(person.Firstname) @(person.Lastname) (@(person.Age)) </span>`

and MainLayout.cshtml (Program cannot find traffic)

`<span>Traffic` : @traffic.Bytes.ToString("N0") `Bytes</span>`

Both seem to be related to Context="person" and Context="traffic". Unfortunately I am not so experienced with web programming and do not know where to look and what to change. What does Context refer to and where can I learn / read more about it ?

Maybe you could have a look and provide a working 2.1 SDK version. Most of the work should have been done.
I attached a 2.1 Version of your project with my changes. I was not sure if a PR would have been better because so many files are involved.

Thank you

   regards

        Uwe

[BlazorTest.zip](https://github.com/SQL-MisterMagoo/BlazorTest/files/2710330/BlazorTest.zip)

**Comment by SQL-MisterMagoo** [comment]
Thanks @uwefms for bringing this to my attention - I have reverted back to 2.1
