### ISSUE TITLE
.net core 2.1 version

### ISSUE THREAD

**Issue by LindaLawton** [SQL-MisterMagoo/BlazorTest#7]
Consider upgrading this to the latest version of 2.1 rather than requiring `"version": "2.1.502"`

```
{
  "sdk": {
    "version": "2.1.700"
  }
}
```

**Comment by SQL-MisterMagoo** [comment]
Thanks for noticing that - I'm actually in the process of updating to 3.0.0-preview6, and I don't have the tooling to test that change on my machine any longer as it's so old, so I will not be able to make that change.

Keep a look out for the update when it's complete though - preview 6 is on the way...

**Comment by LindaLawton** [comment]
I was going to mention that upgrading to .net core 3 would be a good idea i was not able to get this to run changing the version only helped me as far as being able to load the project.
